version: '3'

services:
  thunderrugs:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 17-bullseye
        INSTALL_MAVEN: 'true'
        INSTALL_GRADLE: 'false'
        NODE_VERSION: 18.18.2
    container_name: thunderrugs-devcontainer
    volumes:
      - ..:/workspaces/thunderrugs
      - ~/.m2:/home/vscode/.m2/
      - /etc/localtime:/etc/localtime:ro # volumen para tener la hora actualizada con el host
    # - ../../volumes/wildfly/wildfly-15.0.1.Final:/home/vscode/wildfly/
    command: sleep infinity
