version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=base
      - DATABASE_PASSWORD=1003
      - DATABASE_NAME=alfombras_db
    volumes:
      - ..:/workspaces/Ecommerce
    networks:
      - network_postgresql
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: base
      POSTGRES_PASSWORD: 1003
      POSTGRES_DB: alfombras_db
    networks:
      - network_postgresql

volumes:
  postgres-data:

networks:
  network_postgresql:
    driver: bridge 
